# Keep Ruby version in Dockerfile in sync with Ruby version in Gemfile
FROM ruby:<%= options[:ruby_version] %>
RUN apt-get update -qq && apt-get install -y nodejs postgresql-client
RUN mkdir /app
WORKDIR /app
COPY . /app
RUN bundle install
RUN rake db:seed
RUN rake db:migrate
EXPOSE 3000
# -d (the database url) should match the postgres service name in docker-compose.yml
CMD ["rails", "server", "-b", "0.0.0.0", "-d", "postgresql-server"]
